#Input
print("Hello")
name = input("What is your name?")
age = input("Hi "+name+" How old are you?")
yes = input("Ah. "+age+" is a cool number. Want to see something else cool? Type yes and then hit enter")
#Process

#Output
print("S")
print("So")
print("Sop")
print("Soph")
print("Sophi")
print("Sophiai")
print("Sophiais")
print("Sophiaisa")
print("Sophiaisaw")
print("Sophiaisawe")
print("Sophiaisawes")
print("Sophiaisaweso")
print("Sophiaisawesom")
print("Sophiaisawesome")
print("Sophiaisawesome.")
print("Sophiaisawesome")
print("Sophiaisawesom")
print("Sophiaisaweso")
print("Sophiaisawes")
print("Sophiaisawe")
print("Sophiaisaw")
print("Sophiaisa")
print("Sophiais")
print("Sophiai")
print("Sophia")
print("Sophi")
print("Soph")
print("Sop")
print("So")
print("S")
print("How many lines in this code? Answer to get a special prize!")